Add javax.xml.bind to pom
Without this, java.lang.NoClassDefFoundError occurs due to
missing javax/xml/bind/ValidationException

Solution found in https://stackoverflow.com/questions/43574426